# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97b867d6c3f446c615047ed1609d8a4678d3b0b27d1bc4d520d16ca8acdc1aa21ca06b24082e684070e778071e70f8bc976e2f1d72894a03c596da7792bcffa6

test:
  secret_key_base: cd3a804950eb7e165780c6823a3d75f209e7241c0cd86cc397e444b84b872658fab0a1107aa412d0eec70731d4aeea81dfc00499320efe8c08124356b1c18795

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
